### ISSUE TITLE
Using MCP23S08 library with Arduino_ESP32

### ISSUE THREAD

**Issue by fdxrate** [julianschuler/MCP23S08#4]
First, add this to your Arduino IDE preferences...
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

Second, The sketch will not compile until you add...
#include <Arduino.h>
into the MCP23S08.h and MCP23S08.cpp files.

This is not strictly an issue with the library but rather a prerequisite of 'platform = espressif32' and VS Code/PlatformIO IDE.

**Comment by julianschuler** [comment]
Fixed in 17854b7487.
